### ISSUE TITLE
SSH connection occasionally panics with IO assertion

### ISSUE THREAD

**Issue by benesch** [openssh-rust/openssh#116]
Hey, thanks for a great library! We're using the native-mux implementation in [Materialize](https://github.com/MaterializeInc/materialize), and very occasionally seeing the following panic in our CI:

```
ssh-connection-materialized-1      | thread 'tokio:work-0' panicked at 'min 6 should be no larger than max 0', /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-utility-0.7.5/src/async_read_utility/inner.rs:206:5
ssh-connection-materialized-1      | stack backtrace:
ssh-connection-materialized-1      |    0: rust_begin_unwind
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
ssh-connection-materialized-1      |    1: core::panicking::panic_fmt
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
ssh-connection-materialized-1      |    2: tokio_io_utility::async_read_utility::inner::read_to_container_rng::<alloc::vec::Vec<u8>, tokio::net::unix::stream::UnixStream, core::ops::range::RangeFrom<usize>>
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-utility-0.7.5/src/async_read_utility/inner.rs:206:5
ssh-connection-materialized-1      |    3: tokio_io_utility::async_read_utility::read_to_vec_rng::<tokio::net::unix::stream::UnixStream, core::ops::range::RangeFrom<usize>>
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-io-utility-0.7.5/src/async_read_utility.rs:111:24
ssh-connection-materialized-1      |    4: <openssh_mux_client::connection::Connection>::read_response::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/openssh-mux-client-0.15.5/src/connection.rs:84:13
ssh-connection-materialized-1      |    5: <openssh_mux_client::connection::Connection>::request_port_forward::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/openssh-mux-client-0.15.5/src/connection.rs:405:35
ssh-connection-materialized-1      |    6: <openssh::native_mux_impl::session::Session>::request_port_forward::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/openssh-0.9.8/src/native_mux_impl/session.rs:65:13
ssh-connection-materialized-1      |    7: <openssh::session::Session>::request_port_forward::<openssh::port_forwarding::ForwardType, openssh::port_forwarding::Socket, openssh::port_forwarding::Socket>::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/openssh-0.9.8/src/session.rs:325:13
ssh-connection-materialized-1      |    8: <mz_ssh_util::tunnel::SshTunnelConfig>::connect::{closure#0}
ssh-connection-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a77bbc5f817ef58e-1/materialize/tests/src/ssh-util/src/tunnel.rs:112:17
ssh-connection-materialized-1      |    9: <mz_postgres_util::Config>::connect_internal::<<mz_postgres_util::Config>::connect::{closure#0}::{closure#0}>::{closure#0}
ssh-connection-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a77bbc5f817ef58e-1/materialize/tests/src/postgres-util/src/lib.rs:408:71
ssh-connection-materialized-1      |   10: <mz_postgres_util::Config>::connect::{closure#0}
ssh-connection-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a77bbc5f817ef58e-1/materialize/tests/src/postgres-util/src/lib.rs:368:49
ssh-connection-materialized-1      |   11: mz_postgres_util::drop_replication_slots::{closure#0}
ssh-connection-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a77bbc5f817ef58e-1/materialize/tests/src/postgres-util/src/lib.rs:294:67
ssh-connection-materialized-1      |   12: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}::{closure#0}::{closure#0}
ssh-connection-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a77bbc5f817ef58e-1/materialize/tests/src/adapter/src/coord/ddl.rs:411:33
ssh-connection-materialized-1      |   13: <mz_ore::retry::Retry>::retry_async::<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}::{closure#0}, <mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}::{closure#0}::{closure#0}, core::result::Result<(), mz_postgres_util::PostgresError>, (), mz_postgres_util::PostgresError>::{closure#0}
ssh-connection-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a77bbc5f817ef58e-1/materialize/tests/src/ore/src/retry.rs:240:27
ssh-connection-materialized-1      |   14: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}
ssh-connection-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a77bbc5f817ef58e-1/materialize/tests/src/adapter/src/coord/ddl.rs:413:29
ssh-connection-materialized-1      |   15: <tokio::runtime::task::core::Core<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/core.rs:223:17
ssh-connection-materialized-1      |   16: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}>>>::with_mut::<core::task::poll::Poll<()>, <tokio::runtime::task::core::Core<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll::{closure#0}>
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/loom/std/unsafe_cell.rs:14:9
ssh-connection-materialized-1      |   17: <tokio::runtime::task::core::Core<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/core.rs:212:13
ssh-connection-materialized-1      |   18: tokio::runtime::task::harness::poll_future::<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:476:19
ssh-connection-materialized-1      |   19: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panic/unwind_safe.rs:271:9
ssh-connection-materialized-1      |   20: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>, core::task::poll::Poll<()>>
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
ssh-connection-materialized-1      |   21: std::panicking::try::<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>>
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
ssh-connection-materialized-1      |   22: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>, core::task::poll::Poll<()>>
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
ssh-connection-materialized-1      |   23: tokio::runtime::task::harness::poll_future::<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:464:18
ssh-connection-materialized-1      |   24: <tokio::runtime::task::harness::Harness<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:198:27
ssh-connection-materialized-1      |   25: <tokio::runtime::task::harness::Harness<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#12}::{closure#2}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:152:15
ssh-connection-materialized-1      |   26: <tokio::runtime::task::raw::RawTask>::poll
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/raw.rs:200:18
ssh-connection-materialized-1      |   27: <tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::run
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/mod.rs:394:9
ssh-connection-materialized-1      |   28: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:464:13
ssh-connection-materialized-1      |   29: tokio::runtime::coop::with_budget::<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core>, ()>, <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task::{closure#0}>
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
ssh-connection-materialized-1      |   30: tokio::runtime::coop::budget::<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core>, ()>, <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task::{closure#0}>
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
ssh-connection-materialized-1      |   31: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:463:9
ssh-connection-materialized-1      |   32: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
ssh-connection-materialized-1      |   33: tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
ssh-connection-materialized-1      |   34: <tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::multi_thread::worker::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/macros/scoped_tls.rs:61:9
ssh-connection-materialized-1      |   35: tokio::runtime::scheduler::multi_thread::worker::run
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
ssh-connection-materialized-1      |   36: <tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
ssh-connection-materialized-1      |   37: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/blocking/task.rs:42:21
ssh-connection-materialized-1      |   38: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/core.rs:223:17
ssh-connection-materialized-1      |   39: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>>>::with_mut::<core::task::poll::Poll<()>, <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}>
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/loom/std/unsafe_cell.rs:14:9
ssh-connection-materialized-1      |   40: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/core.rs:212:13
ssh-connection-materialized-1      |   41: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:476:19
ssh-connection-materialized-1      |   42: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panic/unwind_safe.rs:271:9
ssh-connection-materialized-1      |   43: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
ssh-connection-materialized-1      |   44: std::panicking::try::<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>>
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
ssh-connection-materialized-1      |   45: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
ssh-connection-materialized-1      |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
ssh-connection-materialized-1      |   46: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
ssh-connection-materialized-1      |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:464:18
ssh-connection-materialized-1      |   47: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
```

I'm afraid this doesn't reproduce all that readily. Running our SSH tunnel tests in a loop should eventually trigger it, though:

```
git clone https://github.com/MaterializeInc/materialize.git
cd materialize/test/ssh-connection
git checkout bc93581a3680371a8f51345284a6674003823d76
while ./mzcompose run default; do :; done
```

**Comment by NobodyXu** [comment]
This error comes from [`tokio_io_utility::read_to_container_rng`](https://docs.rs/tokio-io-utility/latest/src/tokio_io_utility/async_read_utility/inner.rs.html#185-214), which is there to guard against misuse of the API.

It's called in `<openssh_mux_client::connection::Connection>::read_response`, so it's probably a bug in `openssh_mux_client`.
